version: 2.1
orbs:
  node: circleci/node@4.1.0
  aws-cli: circleci/aws-cli@1.3.1
  eb: circleci/aws-elastic-beanstalk@2.0.1
jobs:
  build:
    docker:
      - image: "cimg/base:stable"
    steps:
      - node/install:
          node-version: '16.13'
      - checkout
      - aws-cli/setup
      - eb/setup
      # install dependencies in both apps
      - run:
          name: udgram-frontend install
          command: |
            npm run frontend:install
      - run:
          name: udgram-backend install
          command: |
            npm run backend:install
      - run:
          name: udgram-frontend build
          command: |
            npm run frontend:build
      - run:
          name: udgram-backend build
          command: |
            npm run backend:build
      - run:
          name: udgram-frontend deploy
          command: |
            npm run frontend:deploy
      - run:
          name: udgram-backend deploy
          command: |
            npm run backend:deploy
